blog/urls.py
from django.urls import path, re_path
from blog import views

app_name = 'blog'
urlpatterns = [

    #Example: /blog/
    path('', views.PostLV.as_view(), name='index',),

    # Example: /blog/post/ (same as /blog/)
    path('post/', views.PostLV.as_view(), name='post_list',),

    # Example: /blog/post/django-example/
    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name='post_detail',),

    #Example: /blog/archive/
    path('archive/', views.PostAV.as_view(), name='post_archive',),

    # Example: /blog/archive/2019/
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive',),

    # Example: /blog/archive/2019/nov/
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive',),

    # Example: /blog/archive/2019/nov/10/
    path('archive/<int:year>/<str:month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive',),

    # Example: /blog/archive/today/
    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive',),

    #Example: /blog/tag/
    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud',),

    #Example: /blog/tag/tagname/
    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(), name='tagged_object_list',),

    # Example: /blog/search
    path('search/', views.SearchFormView.as_view(), name='search',),

    # Example: /blog/add
    path('add/', views.PostCreateView.as_view(), name='add',),

   # Example: /blog/change
    path('change/', views.PostChangeLV.as_view(), name='change',),

   # Example: /blog/99/update
    path('<int:pk>/update/', views.PostUpdateView.as_view(), name='update',),

   # Example: /blog/99/delete
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name='delete',),

]

bookmark/urls.py
from django.urls import path
# from bookmark.views import BookmarkLV, BookmarkDV
from bookmark import views


app_name = 'bookmark'
urlpatterns = [
    path('', views.BookmarkLV.as_view(), name='index'),

    path('bookmark/<int:pk>/', views.BookmarkDV.as_view(), name='bookmark_detail'),

    # Example : /bookmark/add/
    path('bookmark/add/', views.BookmarkCreateView.as_view(), name="bookmark_add"),

    # Example : /bookmark/change/
    path('bookmark/change/', views.BookmarkChangeLV.as_view(), name="bookmark_change"),

    # Example : /bookmark/99/update/
    path('bookmark/<int:pk>/update/', views.BookmarkUpdateView.as_view(), name="bookmark_update"),

    # Example : /bookmark/99/delete/
    path('bookmark/<int:pk>/delete/', views.BookmarkDeleteView.as_view(), name="bookmark_delete"),

    path('marklist/', views.MarklistLV.as_view(), name='marklist_index'),

    path('marklist/<int:pk>/', views.MarklistDV.as_view(), name='marklist_detail'),

    # Example : /marklist/add/
    path('marklist/add/', views.MarkCreateView.as_view(), name="marklist_add"),

    # Example : /marklist/change/
    path('marklist/change/', views.MarkChangeLV.as_view(), name="marklist_change"),

    # Example : /marklist/99/update/
    path('marklist/<int:pk>/update/', views.MarkUpdateView.as_view(), name="marklist_update"),

    # Example : /marklist/99/delete/
    path('marklist/<int:pk>/delete/', views.MarkDeleteView.as_view(), name="marklist_delete"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from mysite.views import HomeView
from mysite.views import UserCreateView, UserCreateDoneTV

from django.conf.urls import include

# from bookmark.views import BookmarkLV, BookmarkDV

urlpatterns = [
    path('admin/', admin.site.urls),
    # sjkim
    path('', HomeView.as_view(), name='home'),
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),
    path('photo/', include('photo.urls')),
    # 인증key
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(),name = 'register_done'),
    path('ckeditor/',include('ckeditor_uploader.urls')),
    # class-based views
    # path('bookmark/', BookmarkLV.as_view(), name = 'index'),
    # path('bookmark/<int:pk>/', BookmarkDV.as_view(), name = 'detail'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

bookmark/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Bookmark(models.Model):
    name = models.CharField('NAME', max_length=100, blank=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)

    class Meta:
        ordering = ('name',)
        
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('bookmark:bookmark_detail', args=(self.id,))


class Marklist(models.Model):
    book = models.ForeignKey(Bookmark,on_delete=models.CASCADE)
    title = models.CharField('title', max_length=100, blank=True)
    url = models.URLField('URL', unique=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)

    class Meta:
        ordering = ('title',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('bookmark:marklist_detail', args=(self.id,))

bookmark/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from bookmark.models import Bookmark, Marklist

from django.views.generic import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from mysite.views import OwnerOnlyMixin

# Create your views here.
class BookmarkLV(LoginRequiredMixin, ListView):
    model = Bookmark

    def get_queryset(self):
        return Bookmark.objects.filter(owner=self.request.user)

class BookmarkDV(DetailView):
    model = Bookmark
    
class MarklistLV(LoginRequiredMixin, ListView):
    model = Marklist

    def get_queryset(self):
        return Marklist.objects.filter(owner=self.request.user)

class MarklistDV(DetailView):
    model = Marklist

class BookmarkCreateView(LoginRequiredMixin, CreateView):
    model = Bookmark
    fields = ['name']
    success_url = reverse_lazy('bookmark:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

 
class BookmarkChangeLV(LoginRequiredMixin, ListView):
    template_name = 'bookmark/bookmark_change_list.html'

    def get_queryset(self):
        return Bookmark.objects.filter(owner=self.request.user)
        
class BookmarkUpdateView(OwnerOnlyMixin, UpdateView):
    model = Bookmark
    fields = ['name']
    success_url = reverse_lazy('bookmark:index')

class BookmarkDeleteView(OwnerOnlyMixin, DeleteView):
    model = Bookmark
    success_url = reverse_lazy('bookmark:index')
    
class MarkCreateView(LoginRequiredMixin, CreateView):
    model = Marklist
    fields = ['book', 'title', 'url']
    success_url = reverse_lazy('bookmark:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

class MarkChangeLV(LoginRequiredMixin, ListView):
    template_name = 'bookmark/marklist_change_list.html'

    def get_queryset(self):
        return Marklist.objects.filter(owner=self.request.user)
        
class MarkUpdateView(OwnerOnlyMixin, UpdateView):
    model = Marklist
    fields = ['book', 'title', 'url']
    success_url = reverse_lazy('bookmark:marklist_index')

class MarkDeleteView(OwnerOnlyMixin, DeleteView):
    model = Marklist
    success_url = reverse_lazy('bookmark:marklist_index')
    

bookmark/templates/bookmark/bookmark_change_list.html
{% extends "base.html" %}

{% block title %}bookmark_change_list.html{% endblock %}

{% block content %}

<h1>Bookmark Change - {{ user }}</h1>
<br>

<table class="table table-bordered table-sm table-striped">

    <thead>
        <tr class="table-primary">
            <th>Title</th>
            <th>Url</th>
            <th>Owner</th>
            <th>Update</th>
            <th>Delete</th>
        </tr>
    </thead>

    <tbody>
        {% for item in object_list %}
        <tr>
            <td>{{ item.title }}</td>
            <td>{{ item.url }}</td>
            <td>{{ item.owner }}</td>
            <td><a href="{% url 'bookmark:update' item.id %}">Update</a></td>
            <td><a href="{% url 'bookmark:delete' item.id %}">Delete</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

bookmark/templates/bookmark/bookmark_confirm_delete.html
{% extends "base.html" %}

{% block title %}bookmark_confirm_delete.html{% endblock %}

{% block content %}

<h1>Bookmark Delete</h1>
<br>

<div>
    <form action="." method="post">{% csrf_token %}
        <p>Are sure you want to delete "{{ object }}" ?</p>
        <input type="submit" value="Confirm" class="btn btn-danger btn-sm" />
    </form>
    
</div>
{% endblock %}

bookmark/templates/bookmark/bookmark_detail.html
{% extends "base.html" %}

{% block title %}Bookmark_detail. html{% endblock %}

{% block content %}
    <h1>{{ object.name }}</h1>
    <br>
    <hr style="margin: 10px o;">
    <ul>
        {% for marklist in object.marklist_set.all %}
           <a href ="{% url 'bookmark:marklist_detail' marklist.id %}"><button type="button" class="btn btn-outline-success">{{ marklist.title }}</button></a>
           
        {% endfor %}
    </ul>
{% endblock %}

bookmark/templates/bookmark/bookmark_form.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}bookmark_form.html{% endblock %}

{% block content %}

    <h1>Bookmark Create/Update - {{ user }}</h1>
    <p class="font-italic"> This is a create or update form for your bookmark. </p>

    {% if form.errors %}
    <div class="alert alert-danger">
        <div class="font-weight-blod">Wrong! Please correct the error(s) below.</div>
        {{ form.errors }}
    </div>
    {% endif %}

<form action="." method="post" class="card pt-3">{% csrf_token %}
    <div class="form-group row">
        {{ form.name|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-blod" }}
        <div>
            {{ form.name|add_class:"form-control"|attr:"autofocus" }}
        </div>
    </div>
    <div class="form-group">
        <div class="offset-sm-2 col-sm-5">
            <input type="submit" value="submit" class="btn btn-info"/>
        </div>
    </div>
</form>

{% endblock %}

bookmark/templates/bookmark/bookmark_list.html
{% extends "base.html" %}

{% block title %}Bookmark_list. html{% endblock %}

{% block content %}
    <h1>Bookmark</h1>
    <br>
    <hr style="margin: 10px o;">
    <ul>
        {% for bookmark in object_list %}
            <a href ="{% url 'bookmark:bookmark_detail' bookmark.id %}"><button type="button" class="btn btn-outline-success">{{ bookmark }}</button></a>
        
        {% endfor %}
    </ul>
{% endblock %}

bookmark/templates/bookmark/marklist_change_list.html
{% extends "base.html" %}

{% block title %}marklist_change_list.html{% endblock %}

{% block content %}

<h1>Marklist Change - {{ user }}</h1>
<br>

<table class="table table-bordered table-sm table-striped">

    <thead>
        <tr class="table-primary">
            <th>Title</th>
            <th>Url</th>
            <th>Owner</th>
            <th>Update</th>
            <th>Delete</th>
        </tr>
    </thead>

    <tbody>
        {% for item in object_list %}
        <tr>
            <td>{{ item.title }}</td>
            <td>{{ item.url }}</td>
            <td>{{ item.owner }}</td>
            <td><a href="{% url 'bookmark:marklist_update' item.id %}">Update</a></td>
            <td><a href="{% url 'bookmark:marklist_delete' item.id %}">Delete</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

bookmark/templates/bookmark/marklist_confirm_delete.html
{% extends "base.html" %}

{% block title %}marklist_confirm_delete.html{% endblock %}

{% block content %}

<h1>marklist_confirm_delete Delete</h1>
<br>

<div>
    <form action="." method="post">{% csrf_token %}
        <p>Are sure you want to delete "{{ object }}" ?</p>
        <input type="submit" value="Confirm" class="btn btn-danger btn-sm" />
    </form>
    
</div>
{% endblock %}

bookmark/templates/bookmark/marklist_detail.html
{% extends "base.html" %}

{% block title %}Marklist_detail. html{% endblock %}

{% block content %}
    <h1>{{ object.title }}</h1>
    <br>
    <hr style="margin: 10px o;">
    <ul>
        <li><div class=""><h4><strong>URL [</strong><a href="{{ object.url }}">{{ object.url }}</a>]</h4></div></li>
    </ul>
{% endblock %}

bookmark/templates/bookmark/marklist_form.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}marklist_form.html{% endblock %}

{% block content %}

    <h1>Marklist Create/Update - {{ user }}</h1>
    <p class="font-italic"> This is a create or update form for your bookmark. </p>

    {% if form.errors %}
    <div class="alert alert-danger">
        <div class="font-weight-blod">Wrong! Please correct the error(s) below.</div>
        {{ form.errors }}
    </div>
    {% endif %}

<form action="." method="post" class="card pt-3">{% csrf_token %}
    <div class="form-group row">
        {{ form.book|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
        <div class="col-sm-2">
            {{ form.book|add_class:"form-control" }}
        </div>
        <div class="col-sm-2 my-auto">
            <a href="{% url 'bookmark:bookmark_add' %}" class="btn btn-outline-primary btn-sm">Add Bookmark</a>
        </div>
    </div>
    <div class="form-group row">
        {{ form.title|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-blod" }}
        <div>
            {{ form.title|add_class:"form-control"|attr:"autofocus" }}
        </div>
    </div>

    <div>
        {{ form.url|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-blod" }}
        <div>
            {{ form.url|add_class:"form-control" }}
        </div>
    </div>

    <div class="form-group">
        <div class="offset-sm-2 col-sm-5">
            <input type="submit" value="submit" class="btn btn-info"/>
        </div>
    </div>
</form>

{% endblock %}

bookmark/templates/bookmark/marklist_list.html
{% extends "base.html" %}

{% block title %}Mark_list.html{% endblock %}

{% block content %}
    <h1>Mark List</h1>
    <br>
    <hr style="margin: 10px o;">
    <ul>
        {% for marklist in object_list %}
            <a href ="{% url 'bookmark:marklist_detail' marklist.id %}"><button type="button" class="btn btn-outline-success">{{ marklist }}</button></a>
        {% endfor %}
    </ul>
{% endblock %}