blog/urls.py
from django.urls import path, re_path
from blog import views

app_name = 'blog'
urlpatterns = [

    #Example: /blog/
    path('', views.PostLV.as_view(), name='index',),

    # Example: /blog/post/ (same as /blog/)
    path('post/', views.PostLV.as_view(), name='post_list',),

    # Example: /blog/post/django-example/
    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name='post_detail',),

    #Example: /blog/archive/
    path('archive/', views.PostAV.as_view(), name='post_archive',),

    # Example: /blog/archive/2019/
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive',),

    # Example: /blog/archive/2019/nov/
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive',),

    # Example: /blog/archive/2019/nov/10/
    path('archive/<int:year>/<str:month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive',),

    # Example: /blog/archive/today/
    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive',),

    #Example: /blog/tag/
    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud',),

    #Example: /blog/tag/tagname/
    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(), name='tagged_object_list',),

    # Example: /blog/search
    path('search/', views.SearchFormView.as_view(), name='search',),

    # Example: /blog/add
    path('add/', views.PostCreateView.as_view(), name='add',),

   # Example: /blog/change
    path('change/', views.PostChangeLV.as_view(), name='change',),

   # Example: /blog/99/update
    path('<int:pk>/update/', views.PostUpdateView.as_view(), name='update',),

   # Example: /blog/99/delete
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name='delete',),

]

bookmark/urls.py
from django.urls import path
# from bookmark.views import BookmarkLV, BookmarkDV
from bookmark import views


app_name = 'bookmark'
urlpatterns = [
    path('', views.BookmarkLV.as_view(), name='index'),

    path('bookmark/<int:pk>/', views.BookmarkDV.as_view(), name='bookmark_detail'),

    # Example : /bookmark/add/
    path('bookmark/add/', views.BookmarkCreateView.as_view(), name="bookmark_add"),

    # Example : /bookmark/change/
    path('bookmark/change/', views.BookmarkChangeLV.as_view(), name="bookmark_change"),

    # Example : /bookmark/99/update/
    path('bookmark/<int:pk>/update/', views.BookmarkUpdateView.as_view(), name="bookmark_update"),

    # Example : /bookmark/99/delete/
    path('bookmark/<int:pk>/delete/', views.BookmarkDeleteView.as_view(), name="bookmark_delete"),

    path('marklist/', views.MarklistLV.as_view(), name='marklist_index'),

    path('marklist/<int:pk>/', views.MarklistDV.as_view(), name='marklist_detail'),

    # Example : /marklist/add/
    path('marklist/add/', views.MarkCreateView.as_view(), name="marklist_add"),

    # Example : /marklist/change/
    path('marklist/change/', views.MarkChangeLV.as_view(), name="marklist_change"),

    # Example : /marklist/99/update/
    path('marklist/<int:pk>/update/', views.MarkUpdateView.as_view(), name="marklist_update"),

    # Example : /marklist/99/delete/
    path('marklist/<int:pk>/delete/', views.MarkDeleteView.as_view(), name="marklist_delete"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from mysite.views import HomeView
from mysite.views import UserCreateView, UserCreateDoneTV

from django.conf.urls import include

# from bookmark.views import BookmarkLV, BookmarkDV

urlpatterns = [
    path('admin/', admin.site.urls),
    # sjkim
    path('', HomeView.as_view(), name='home'),
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),
    path('photo/', include('photo.urls')),
    # 인증key
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(),name = 'register_done'),
    path('ckeditor/',include('ckeditor_uploader.urls')),
    # class-based views
    # path('bookmark/', BookmarkLV.as_view(), name = 'index'),
    # path('bookmark/<int:pk>/', BookmarkDV.as_view(), name = 'detail'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

photo/urls.py
from django.urls import path
from django.views.generic import ListView, DetailView
from photo.models import Album, Photo

from photo import views

app_name = 'photo'
urlpatterns = [

    #Example: /photo/
    path('', views.AlbumLV.as_view(), name='index'),

    # Example: /photo/album/ (same as /photo/)
    path('album/', views.AlbumLV.as_view(), name='album_list'),

    # Example: /photo/album/99/
    path('album/<int:pk>/', views.AlbumDV.as_view(), name='album_detail'),

    # Example: /photo/photo/99/
    path('photo/<int:pk>/', views.PhotoDV.as_view(), name='photo_detail'),

    # Example: /photo/album/add/
    path('album/add/', views.AlbumPhotoCV.as_view(), name='album_add'),

    # Example: /photo/album/change
    path('album/change/', views.AlbumChangeLV.as_view(), name='album_change'),

    # Example: /photo/album/99/update/
    path('album/<int:pk>/update/', views.AlbumPhotoUV.as_view(), name='album_update'),

    # Example: /photo/album/99/delete/
    path('album/<int:pk>/delete/', views.AlbumDelV.as_view(), name='album_delete'),

    # Example: /photo/photo/add/
    path('photo/add/', views.PhotoCV.as_view(), name='photo_add'),

    # Example: /photo/photo/change
    path('photo/change/', views.PhotoChangeLV.as_view(), name='photo_change'),

    # Example: /photo/photo/99/update/
    path('photo/<int:pk>/update/', views.PhotoUV.as_view(), name='photo_update'),

    # Example: /photo/photo/99/delete/
    path('photo/<int:pk>/delete/', views.PhotoDelV.as_view(), name='photo_delete'),

]

templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name='viewport' content="width=device-width, inntal-scale=1">
        <title>{% block title %}MidasCM{% endblock %}</title>
        <link rel="icon" href="/static/img/favicon.ico">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" >
        {% block extra-style %}{% endblock %}
</head>

<body style="padding-top:80px;">
    
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <span class="navbar-brand mx-5 mb-0 font-weigt-bold font-italic">MidasCM</span>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
          <ul class="navbar-nav mr-auto  ">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'bookmark:index' %}">Bookmark</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'blog:index' %}">Blog</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'photo:index' %}">Photo</a>
            </li>
           
            <li class="nav-item dropdown btn btn-sm mx-1">
              <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">Add</a>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'bookmark:bookmark_add' %}">Bookmark</a>
                <a class="dropdown-item" href="{% url 'bookmark:marklist_add' %}">Marklist</a>
                <a class="dropdown-item" href="{% url 'blog:add' %}">Post</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'photo:album_add' %}">Album</a>
                <a class="dropdown-item" href="{% url 'photo:photo_add' %}">Photo</a>
              </div>
            </li>
           
            <li class="nav-item dropdown btn btn-sm mx-1">
              <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">Change</a>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'bookmark:bookmark_change' %}">Bookmark</a>
                <a class="dropdown-item" href="{% url 'bookmark:marklist_change' %}">Marklist</a>
                <a class="dropdown-item" href="{% url 'blog:change' %}">Post</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'photo:album_change' %}">Album</a>
                <a class="dropdown-item" href="{% url 'photo:photo_change' %}">Photo</a>
              </div>
            </li>
            <li class="nav-item dropdown btn btn-sm mx-1">
              <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">Util</a>
              <div class="dropdown-menu">
                  <a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'blog:post_archive' %}">Archive</a>
                  <a class="dropdown-item" href="{% url 'blog:search' %}">Search</a>
              </div>
            </li>
          </ul>
          

      <ul class="navbar-nav ml-5 mr-5">
        <li class = "nav-item dropdown mx-1 btn btn-primary">
            {% if user.is_active %}
              <a class = "nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">
                <i class="far fa-user"></i>&ensp;{% firstof user.get_short_name user.get_username %}&ensp;
              </a>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                <a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a>
              </div>
            {% else %}
                <a class="nav-link dropdown-toggle text-white" href = "#" data-toggle="dropdown">
                  <i class="far fa-user"></i>&ensp;Anonymous&ensp;</a>
              <div class="dropdown-menu">
                  <a class="dropdown-item" href="{% url 'login' %}">Login</a>
                  <a class="dropdown-item" href="{% url 'register' %}">Register</a>
              </div>
            {% endif %}
        </li>
      </ul>
    </div>
  </nav>
     <div class="container">
        {% block content %}{% endblock %}
     </div>

     <footer class="container bg-warning">
        {% block footer %}{% endblock %}
    </footer>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" ></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" ></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" ></script>
    <script src="https;//kit.fontawesome.com/c998a172fe.js"></script>
    <script id="dsq-count-scr" src="//midascm-2.disqus.com/count.js" async></script>
    {% block extra-script %}{% endblock %}

</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}home.html{% endblock %}

{% block extra-style %}
<style type="text/css">
.home-image {
    background-image: url("{% static 'img/sheep.jpg' %}");
    background-repeat: no-repeat;
    background-position: center;
    background-size: 100%;
    height: 500px;
    border-top: 0px solid rgb(255, 255, 255);
    border-bottom: 0px solid rgb(255, 255, 255);
    padding: 0 0 0 0;
}
.title {
    color: #c80;
    font-weight: bold;
}
.powered {
    position: relative;
    top: 77%;
    color: #cc0;
    font-style: italic;
}
</style>
{% endblock %}

{% block content %}
<div id="demo" class="carousel slide" data-ride="carousel">
  <ul class="carousel-indicators">
    <li data-target="#demo" data-slide-to="0" class="active"></li>
    <li data-target="#demo" data-slide-to="1"></li>
    <li data-target="#demo" data-slide-to="2"></li>
  </ul>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{% static 'img/blog.jpg' %}" alt="blog app" width="100%" height="100%">
      <div class="carousel-caption">
        <h3>Blog</h3>
        <p>생각을 기록하라!</p>
      </div>
    </div>
    <div class="carousel-item">
     <img src="{% static 'img/photo.jpg' %}" alt="photo app" width="100%" height="100%">
      <div class="carousel-caption">
        <h3>Photo App</h3>
        <p>순간의 선택!</p>
      </div>
    </div>
    <div class="carousel-item">
     <img src="{% static 'img/bookmark.jpg' %}" alt="bookmark app" width="100%" height="100%">
      <div class="carousel-caption">
        <h3>Bookmark App</h3>
        <p>자주가는 사이트!</p>
      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#demo" data-slide="prev">
    <span class="carousel-control-prev-icon"></span>
  </a>
  <a class="carousel-control-next" href="#demo" data-slide="next">
    <span class="carousel-control-next-icon"></span>
  </a>
</div>

<hr style="margin: 10px o;">

<div class="row text-center">
  <div class="col-sm-4 bg-">
    <a href="{% url 'bookmark:index' %}"><h3>Bookmark</h3></a>
    <hr style="margin: 10px o;">
    <p>According to new results of the research done on the history of bookmarks,
       there are indications that bookmarks have accompanied codices since their first
       emergence in the 1st century AD.[1] The earliest existing bookmark dates from
       the 6th century AD and it is made of ornamented leather lined with vellum on the back
       </p>
  
  </div>
  <div class="col-sm-4 bg-">
    <a href="{% url 'blog:index' %}"><h3>Blog</h3></a>
    <hr style="margin: 10px o;">
    <p>According to new results of the research done on the history of bookmarks,
       there are indications that bookmarks have accompanied codices since their first
       emergence in the 1st century AD.[1] The earliest existing bookmark dates from
       the 6th century AD and it is made of ornamented leather lined with vellum on the back
       </p>
  </div>
  <div class="col-sm-4 bg-">
    <a href="{% url 'photo:index' %}"><h3>Photo</h3></a>
    <hr style="margin: 10px o;">
    <p>According to new results of the research done on the history of bookmarks,
       there are indications that bookmarks have accompanied codices since their first
       emergence in the 1st century AD.[1] The earliest existing bookmark dates from
       the 6th century AD and it is made of ornamented leather lined with vellum on the back
       </p>
  </div>
  </div>
{% endblock %}

{% block footer %}
<footer class="fixed-bottom bg-info">
  <div class="text-white font-italic text-right mr-5">Copyright & copy; 2020 MidasCM by sjkim</div>
</footer>
{% endblock %}
     